### ISSUE TITLE
deskewGPU function removed from docs?

### ISSUE THREAD

**Issue by avenkatramani** [tlambert03/pycudadecon#25]
Just noticed that the latest doc update removed the deskewGPU function. Is it still supported?

**Comment by tlambert03** [comment]
Yeah it's still [there](url) ... can you point me to where it seemed like it got removed? (so I can maybe prevent the confusion?)

**Comment by avenkatramani** [comment]
Thanks! I was using - https://pycudadecon.readthedocs.io/_/downloads/en/latest/pdf/ for reference and it looks like the update last week removed it.

**Comment by tlambert03** [comment]
ah... ok thanks!  yeah, I need to refresh the docs at readthedocs.  will likely be doing a little more cleanup in the near future, and will update the docs after that.  but I don't plan to make any breaking changes (maybe some naming changes/deprecations, but no functionality).  Thanks!

**Comment by tlambert03** [comment]
ok, docs are updated now, and hosted here: http://www.talleylambert.com/pycudadecon/

affine page is fixed again: http://www.talleylambert.com/pycudadecon/affine.html
