### ISSUE TITLE
units used

### ISSUE THREAD

**Issue by F-S-Menezes** [tlambert03/pycudadecon#35]
i am attempting to use the deskewGPU, and whilst it works fantastically, i wish to fine-tune my results to the microscope being used and so use the optional arguments. however, i can not see anywhere what units you are using? would it be correct to assume arguments such as dxdata, dzdata, and shift are in microns?

**Comment by tlambert03** [comment]
For deskewing, what really matters is the _ratio_ of dxdata and dzdata.  so, I believe it should work regardless of your units, as long as dx and dz are in the same units.  That is I think `deskewGPU(..., dxdata=100, dzdata=500)` should give the same result as `deskewGPU(..., dxdata=.1, dzdata=.5)`.  (but let me know if that doesn't seem to match your experience).  `shift` and `width` are in units of pixels.

**Comment by F-S-Menezes** [comment]
thank you for the swift response! i will close this issue once i have checked against some test files
