### ISSUE TITLE
Temporary File write error

### ISSUE THREAD

**Issue by gdellaire** [tlambert03/pycudadecon#4]
Thanks for making this software available.

I did an install on a Win10 machine with Anaconda Python 3.7
After the CONDA install for PyCUDAdecon, it seems to have gone okay but there is a write permission error when the following code is run (from the GitHub documentation):

`from pycudadecon import decon
image_path = '/path/to/some_image.tif'
psf_path = '/path/to/psf_3D.tif'
result = decon(image_path, psf_path)`

This returns a PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpqs067x60.tif'

I tried running CONDA as Administrator, I looked at permissions and everything is read/write for Admin and all Users.

So I am not sure what is going on. It might be better to have the temp files written to another directory that is not write protected such as  %LocalAppData%. 

Anyway, thought you might like to know about this error on Windows installations.

Best
Graham

**Comment by tlambert03** [comment]
Thanks Graham, yeah someone else alluded to that on twitter.  
Looks like python's NamedTemporaryFile object is a bit [crippled on windows](https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file#) unfortunately.  i'll figure out a workaround.  Ultimately, I'll try to avoid file I/O all together for the OTF... but that will take a little bit of doing on the library side.  

If you have a minute, could you paste the full traceback here?

**Comment by gdellaire** [comment]
Sure... here you go:

`PermissionError                           Traceback (most recent call last)
<ipython-input-2-bbf66be06aa7> in <module>
      4 print("Execution Time:")
      5 
----> 6 result = decon(image_path, psf_path)
      7 
      8 # end timing of BBii reconstruction

~\Anaconda3\lib\site-packages\pycudadecon\deconvolution.py in decon(images, psf, fpattern, **kwargs)
    137 
    138     out = []
--> 139     with TemporaryOTF(psf, **kwargs) as otf:
    140         arraygen = _yield_arrays(images)
    141         # first, assume that all of the images are the same shape...

~\Anaconda3\lib\site-packages\pycudadecon\otf.py in __enter__(self)
    273                     make_otf(temp_psf.name, self.tempotf.name, **self.kwargs)
    274             elif isinstance(self.psf, str) and os.path.isfile(self.psf):
--> 275                 make_otf(self.psf, self.tempotf.name, **self.kwargs)
    276             else:
    277                 raise ValueError("Did not expect PSF file as {}".format(type(self.psf)))

~\Anaconda3\lib\site-packages\pycudadecon\otf.py in make_otf(psf, outpath, dzpsf, dxpsf, wavelength, na, nimm, otf_bgrd, krmax, fixorigin, cleanup_otf, max_otf_size, **kwargs)
    214         psf = temp_psf.name
    215 
--> 216     with CappedPSF(psf, max_otf_size) as _psf:
    217         shared_makeotf(
    218             str.encode(_psf.path),

~\Anaconda3\lib\site-packages\pycudadecon\otf.py in __enter__(self)
    149         if isinstance(self.psf, np.ndarray):
    150             self.temp_psf = tempfile.NamedTemporaryFile(suffix=".tif")
--> 151             tf.imsave(self.temp_psf.name, cap_psf_size(self.psf, self.max_otf_size))
    152             self.path = self.temp_psf.name
    153         return self

~\AppData\Roaming\Python\Python37\site-packages\tifffile\tifffile.py in imwrite(file, data, shape, dtype, bigsize, **kwargs)
    685         tifargs['byteorder'] = byteorder
    686 
--> 687     with TiffWriter(file, **tifargs) as tif:
    688         return tif.save(data, shape, dtype, **kwargs)
    689 

~\AppData\Roaming\Python\Python37\site-packages\tifffile\tifffile.py in __init__(self, file, bigtiff, byteorder, append, imagej)
    891             self._fh.seek(0, 2)
    892         else:
--> 893             self._fh = FileHandle(file, mode='wb', size=0)
    894             self._fh.write({'<': b'II', '>': b'MM'}[byteorder])
    895             if bigtiff:

~\AppData\Roaming\Python\Python37\site-packages\tifffile\tifffile.py in __init__(self, file, mode, name, offset, size)
   5140         self.is_file = False
   5141         self._lock = NullContext()
-> 5142         self.open()
   5143 
   5144     def open(self):

~\AppData\Roaming\Python\Python37\site-packages\tifffile\tifffile.py in open(self)
   5153             self._file = os.path.realpath(self._file)
   5154             self._dir, self._name = os.path.split(self._file)
-> 5155             self._fh = open(self._file, self._mode)
   5156             self._close = True
   5157             if self._offset is None:

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpicp461cf.tif'
`
Best G.

**Comment by bryantChhun** [comment]
for what it's worth, i'm also seeing this problem :-/

**Comment by tlambert03** [comment]
Hey bryant!  long time no see :)
thanks for letting me know.

**Comment by bryantChhun** [comment]
for sure :-) We need to sync up.  will find a way to DM you

**Comment by tlambert03** [comment]
ok, I made some changes that should fix it.  when you have a minute update with 
`conda update pycudadecon` and let me know if it works for you.

**Comment by gdellaire** [comment]
Hi - I did the update and I am getting the following trace and WinError.
Seems like a compile error maybe? 

'Start PyCUDAdecon
Execution Time:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-1956c354337e> in <module>
      4 print("Execution Time:")
      5 
----> 6 result = decon(image_path, psf_path)
      7 
      8 # end timing of PyCUDAdecon deconvolution

~\Anaconda3\lib\site-packages\pycudadecon\deconvolution.py in decon(images, psf, fpattern, **kwargs)
    147         with RLContext(shp, otf.path, **kwargs) as ctx:
    148             while True:
--> 149                 out.append(rl_decon(next_im, output_shape=ctx.out_shape, **kwargs))
    150                 try:
    151                     next_im = next(arraygen)

~\Anaconda3\lib\site-packages\pycudadecon\libcudawrapper.py in rl_decon(im, background, n_iters, shift, save_deskewed, output_shape, napodize, nz_blend, pad_val, dup_rev_z, **kwargs)
    239         nz_blend,
    240         pad_val,
--> 241         dup_rev_z,
    242     )
    243 

OSError: [WinError -529697949] Windows Error 0xe06d7363

`

**Comment by tlambert03** [comment]
I haven't been able to reproduce this one after trying on a couple different PCs...  That win error code is something that [cropped up for LLSpy](https://github.com/tlambert03/LLSpy/issues/2)... but I can't think why it would be affecting pycudadecon.  Are you importing anything else?  Could you send me the full code you are using (including any imports) to invoke pycudadecon.decon?  and also check which version of llspylibs was installed (at the conda prompt `conda list llspylibs`).

**Comment by gdellaire** [comment]
I tried on a second machine... Win10

Cuda 9.0 Toolkit 
llsplibs - 0.2.0
Test images - http://bigwww.epfl.ch/deconvolution/bars/
Running Jupyter for testing the code in Anaconda

Code: 
`from pycudadecon import decon
image_path = 'D:\Dropbox\ARCHIVE\BBII algorithm\BenchMarks\Synthetic Bars EPFL\Bars-G10-P30-stack.tif'
psf_path = 'D:\Dropbox\ARCHIVE\BBII algorithm\BenchMarks\Synthetic Bars EPFL\PSF-Bars-stack.tif'`

No errors

Then running: 
`result = decon(image_path, psf_path)`

This then causes the same OSError (EXACT SAME as above).

But pycudadecon is not generically broken as this code below works:

`OTF = make_otf(psf_path)`

Not sure what is going on but really appreciate you working on this, and I am happy to keep bashing away with your aid to get this working on Win10.  Maybe @bryantChhun has had more luck.

**Comment by tlambert03** [comment]
Graham, what's your GPU and driver version?

**Comment by chalkie666** [comment]
Me too.

Cheets

D

**Comment by tlambert03** [comment]
you too what, same windows error?
please provide more information if reporting a bug.  
operating system version, GPU, driver, environment... jupyter or not... etc.

**Comment by bryantChhun** [comment]
Hi guys,

I updated my pycuda decon just as Talley said above.  It works fine now.  Sorry that it's not the case for all :-(

I'm running Windows 10, Cuda10.1 with appropriate cudnn

**Comment by tlambert03** [comment]
In LLSpy, this error occurred when two different resources were fighting for the same GPU... so my suspicion is that something about your environments are clashing.  If you're running this in a Jupyter Notebook (as opposed to an interactive ipython session or something), that's important information.  In addition to the information requested above, it would be helpful if you could paste your full environment info (run `conda list` and paste the output here... using the "insert code" format)

**Comment by tlambert03** [comment]
Since the temporary file write error seems fixed, I'm going to create a [new issue](https://github.com/tlambert03/pycudadecon/issues/5) for this.  Please post any new information over there.  Thanks

**Comment by chalkie666** [comment]
Sorry Talley.
I should know better.

Win 10, 64 bit
Anconda install
Running from anaconda command prompt with
python script.py
Style execution of a script like your example.
Permissions error, can't write to appdata/temp

This was last friday


I will try your updated stuff next week.


Best

Da

**Comment by tlambert03** [comment]
oh, i see.  Yeah that's fixed in v0.1.2
