### ISSUE TITLE
Task: implement decon-before-deskew

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/pycudadecon#43]
tracking support for https://github.com/scopetools/cudadecon/pull/23 on the python side

**Comment by zichenzachwang** [comment]
Hi Talley,

I noticed that in 0.4.1 release you mentioned there is added support for sample-scan decon before deskew. I recently tried adding skewed_decon=True with 3D sample-scan PSF acquired on MOSAIC. However, the kernel crashed after I tried, aparently due to some memory issue. I have tested with cudaDecon and it worked. I am wondering if this is some functionality you have already added or still in development. I can provide more information if it is supposed to work.

Zach

**Comment by tlambert03** [comment]
hey @zichenzachwang.  I think @dmilkie did expose support for skewed-decon https://github.com/tlambert03/pycudadecon/pull/47. I admit I haven't had time to try it yet, perhaps he can weigh in?  @dmilkie, have you been using skewed decon via pycudadecon successfully?   Does it still need tweaking?  If anyone has or could generate a very small test dataset that we could add [to test_data](https://github.com/tlambert03/pycudadecon/tree/main/tests/test_data) that would be a nice bonus :)

then we can discuss the kernel crash that @zichenzachwang is observing

**Comment by zichenzachwang** [comment]
Hi guys thanks for the help! I took a closer look at both repositories and noticed something. In cudaDecon [#23](https://github.com/scopetools/cudadecon/commit/e79e98d53985b210e4c47555c4ebbfb568028daa), [radialft_interface.cpp](https://github.com/scopetools/cudadecon/blob/main/src/radialft_interface.cpp) was not get changed the the same way Linshao did for [radialft-nonSIM.cpp](https://github.com/scopetools/cudadecon/blob/main/src/radialft-nonSIM.cpp). That way the libradialft in pycudadecon is not updated (need b3Dout arg and some fix_origin modifications). Also I think in pycudadecon [_libwrap.py](https://github.com/tlambert03/pycudadecon/blob/main/src/pycudadecon/_libwrap.py) and [otf.py](https://github.com/tlambert03/pycudadecon/blob/main/src/pycudadecon/otf.py) needs to add support for 3D OTF. I rebuilt cudaDecon and it seems to work very well. Let me know if you think this is the issue. I am happy to share my modified codes if want.

**Comment by zichenzachwang** [comment]
> I thought it was as simple as adding support for thre flag, but it was a little more than that. I’m in the middle of confirming it’s working. I need to double check that the OTF scaling (with OTF voxel size) is working properly before pushing it up. I have not seen a “kernel crash”. What is the error message?-DanOn Nov 3, 2023, at 10:38 AM, Talley Lambert ***@***.***> wrote:﻿ hey @zichenzachwang. I think @dmilkie did expose support for skewed-decon #47. I admit I haven't had time to try it yet, perhaps he can weigh in? @dmilkie, have you been using skewed decon via pycudadecon successfully? Does it still need tweaking? If anyone has or could generate a very small test dataset that we could add to test_data that would be a nice bonus :) then we can discuss the kernel crash that @zichenzachwang is observing —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

I am using jupyter notebook on Ubuntu and it wasn't clear to me. No explicit error message and certainly not memory issue.

**Comment by dmilkie** [comment]
I (probably) did the same thing.  
https://github.com/dmilkie/cudaDecon/commit/ff7a039a994a667112ea3a484e9431510cce4ee9
https://github.com/dmilkie/pycudadecon/commit/ca52c146a7406f9c518e95254e9a2c354a407191
My current state of code is on my two branches there.

**Comment by zichenzachwang** [comment]
> I (probably) did the same thing. [dmilkie/cudaDecon@ff7a039](https://github.com/dmilkie/cudaDecon/commit/ff7a039a994a667112ea3a484e9431510cce4ee9) [dmilkie@ca52c14](https://github.com/dmilkie/pycudadecon/commit/ca52c146a7406f9c518e95254e9a2c354a407191) My current state of code is on my two branches there.

Right that will be great! I couldn't build it myself on Windows though so I will probably wait for your official release. Thanks a lot.

**Comment by zichenzachwang** [comment]
> I (probably) did the same thing. [dmilkie/cudaDecon@ff7a039](https://github.com/dmilkie/cudaDecon/commit/ff7a039a994a667112ea3a484e9431510cce4ee9) [dmilkie@ca52c14](https://github.com/dmilkie/pycudadecon/commit/ca52c146a7406f9c518e95254e9a2c354a407191) My current state of code is on my two branches there.

Hi Dan,
I am curious how your tests went. Do you think you may release new versions of cudadeon and pycudadecon with functional sample stage decon sometime soon? That would be very helpful thx!
Zach

**Comment by dmilkie** [comment]
It's still on my todo list. Hopefully get to it next week.

**Comment by zichenzachwang** [comment]
Hi Dan,

Just a reminder to see if you will be able to fix this issue and update pycudadecon soon. Thanks!

Zach
________________________________

**Comment by tlambert03** [comment]
sounds like this is now complete thanks to @zichenzachwang's work in #57 and elsewhere, correct @zichenzachwang ?

**Comment by zichenzachwang** [comment]
> sounds like this is now complete thanks to @zichenzachwang's work in #57 and elsewhere, correct @zichenzachwang ?

Yes! Tested on my end and works well.
