### ISSUE TITLE
OSError: [WinError -529697949] Windows Error 0xe06d7363

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/pycudadecon#5]
### Update

It appears that this issue can occur if you have installed pycudadecon into your _base_ conda environment.  Try installing pycudadecon into a fresh dedicated environment as [described below](#issuecomment-472169392).

---------------------------------------------------------------------------
_Originally posted by @gdellaire in https://github.com/tlambert03/pycudadecon/issues/4#issuecomment-471961062_

I am getting the following trace and WinError when running pycudadecon.decon in a jupyter console on Win10.

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-1956c354337e> in <module>
      4 print("Execution Time:")
      5 
----> 6 result = decon(image_path, psf_path)
      7 
      8 # end timing of PyCUDAdecon deconvolution

~\Anaconda3\lib\site-packages\pycudadecon\deconvolution.py in decon(images, psf, fpattern, **kwargs)
    147         with RLContext(shp, otf.path, **kwargs) as ctx:
    148             while True:
--> 149                 out.append(rl_decon(next_im, output_shape=ctx.out_shape, **kwargs))
    150                 try:
    151                     next_im = next(arraygen)

~\Anaconda3\lib\site-packages\pycudadecon\libcudawrapper.py in rl_decon(im, background, n_iters, shift, save_deskewed, output_shape, napodize, nz_blend, pad_val, dup_rev_z, **kwargs)
    239         nz_blend,
    240         pad_val,
--> 241         dup_rev_z,
    242     )
    243 

OSError: [WinError -529697949] Windows Error 0xe06d7363
```

**Comment by tlambert03** [comment]
**If posting this issue, please include the following information**

- OS version
- GPU version and driver
- specifics about the environment in which you're running the program (script, jupyter, ipython, etc...)
- paste the result of the command `conda list` in your conda environment

**Comment by gdellaire** [comment]
Hi Tally

**OS:** Win10 x64 build version 1803
**GPU** Nvidia Titan Xp Driver: 385.54 (will try upgrading to latest driver)
CUDA Toolkit 9.0

Environment: Anaconda 64-bit Python 3.7 - using both Jupyter and Spyder
Conda List:
(base) C:\WINDOWS\system32>conda list
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.11                   py37_0
anaconda                  5.3.0                    py37_0
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.6                    py37_0
anaconda-project          0.8.2                    py37_0
appdirs                   1.4.3            py37h28b3542_0
asn1crypto                0.24.0                   py37_0
astroid                   2.0.4                    py37_0
astropy                   3.0.4            py37hfa6e2cd_0
atomicwrites              1.2.1                    py37_0
attrs                     18.2.0           py37h28b3542_0
automat                   0.7.0                    py37_0
babel                     2.6.0                    py37_0
backcall                  0.1.0                    py37_0
backports                 1.0                      py37_1
backports.shutil_get_terminal_size 1.0.0                    py37_2
beautifulsoup4            4.6.3                    py37_0
bitarray                  0.8.3            py37hfa6e2cd_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
blaze                     0.11.3                   py37_0
bleach                    2.1.4                    py37_0
blosc                     1.14.4               he51fdeb_0
bokeh                     0.13.0                   py37_0
boto                      2.49.0                   py37_0
bottleneck                1.2.1            py37h452e1ab_1
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.11.5           py37h74b6da3_1
chardet                   3.0.4                    py37_1
click                     6.7                      py37_0
cloudpickle               0.5.5                    py37_0
clyent                    1.2.2                    py37_1
colorama                  0.3.9                    py37_0
comtypes                  1.1.7                    py37_0
conda                     4.6.8                    py37_0    conda-forge
conda-build               3.15.1                   py37_0
conda-env                 2.6.0                h36134e3_1
console_shortcut          0.1.1                         3
constantly                15.1.0           py37h28b3542_0
contextlib2               0.5.5                    py37_0
cryptography              2.5              py37h7a1dbc1_0
cudatoolkit               10.0.130                      0
curl                      7.63.0            h2a8f88b_1000
cycler                    0.10.0                   py37_0
cython                    0.28.5           py37h6538335_0
cytoolz                   0.9.0.1          py37hfa6e2cd_1
dask                      0.19.1                   py37_0
dask-core                 0.19.1                   py37_0
datashape                 0.5.4                    py37_1
decorator                 4.3.0                    py37_0
defusedxml                0.5.0                    py37_1
distributed               1.23.1                   py37_0
docutils                  0.14                     py37_0
entrypoints               0.2.3                    py37_2
et_xmlfile                1.0.1                    py37_0
fastcache                 1.0.2            py37hfa6e2cd_2
fftw                      3.3.8             hfa6e2cd_1003    conda-forge
filelock                  3.0.8                    py37_0
flask                     1.0.2                    py37_1
flask-cors                3.0.6                    py37_0
freetype                  2.9.1                ha9979f8_1
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.3.6            py37hfa6e2cd_0
glob2                     0.6                      py37_0
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.8.0            py37h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py37_2
html5lib                  1.0.1                    py37_0
hyperlink                 18.0.0                   py37_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py37_0
imagecodecs               2019.1.20                pypi_0    pypi
imageio                   2.4.1                    py37_0
imagesize                 1.1.0                    py37_0
imglyb                    0.3.4           py37h39e3cac_1000    conda-forge
incremental               17.5.0                   py37_0
intel-openmp              2019.0                      118
ipykernel                 4.10.0                   py37_0
ipython                   6.5.0                    py37_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.4.1                    py37_0
isort                     4.3.4                    py37_0
itsdangerous              0.24                     py37_1
jdcal                     1.4                      py37_0
jedi                      0.12.1                   py37_0
jgo                       0.3.0                 py37_1000    conda-forge
jinja2                    2.10                     py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.3                    py37_0
jupyter_console           5.2.0                    py37_1
jupyter_core              4.4.0                    py37_0
jupyterlab                0.34.9                   py37_0
jupyterlab_launcher       0.13.1                   py37_0
keyring                   13.2.1                   py37_0
kiwisolver                1.0.1            py37h6538335_0
krb5                      1.16.1               hc04afaa_7
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
libboost                  1.67.0               hd9e427e_4
libcurl                   7.63.0            h2a8f88b_1000
libiconv                  1.15                 h1df5818_7
libpng                    1.6.36            h7602738_1000    conda-forge
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0             h642c060_1004    conda-forge
libtiff                   4.0.9                h36446d0_2
libxcb                    1.13              h301d43c_1002    conda-forge
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llspylibs                 0.2.0                         0    talley
llvmlite                  0.24.0           py37h6538335_0
locket                    0.2.0                    py37_1
lxml                      4.2.5            py37hef2cd61_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.0              py37hfa6e2cd_1
matplotlib                3.0.3                    py37_0    conda-forge
matplotlib-base           3.0.3            py37h3e3dc42_0    conda-forge
maven                     3.6.0                         0    conda-forge
mccabe                    0.6.1                    py37_1
menuinst                  1.4.14           py37hfa6e2cd_0
mistune                   0.8.3            py37hfa6e2cd_1
mkl                       2019.1                      144
mkl-service               1.1.2            py37hb217b18_5
mkl_fft                   1.0.10           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
more-itertools            4.3.0                    py37_0
mpmath                    1.0.0                    py37_2
msgpack-python            0.5.6            py37he980bc4_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.4.0                    py37_1
nbformat                  4.4.0                    py37_0
networkx                  2.1                      py37_0
nltk                      3.3.0                    py37_0
nose                      1.3.7                    py37_2
notebook                  5.6.0                    py37_0
numba                     0.39.0           py37h830ac7b_0
numexpr                   2.6.8            py37h9ef55f4_0
numpy                     1.16.2                   pypi_0    pypi
numpy-base                1.16.2           py37hc3f5095_0
numpydoc                  0.8.0                    py37_0
odo                       0.5.1                    py37_0
olefile                   0.46                     py37_0
openjdk                   11.0.1          c_compilervs2015_1014    conda-forge
openpyxl                  2.5.6                    py37_0
openssl                   1.1.1b               hfa6e2cd_1    conda-forge
packaging                 17.1                     py37_0
pandas                    0.23.4           py37h830ac7b_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2                    py37_1
parso                     0.3.1                    py37_0
partd                     0.3.8                    py37_0
path.py                   11.1.0                   py37_0
pathlib2                  2.3.2                    py37_0
patsy                     0.5.0                    py37_0
pep8                      1.7.1                    py37_0
pickleshare               0.7.4                    py37_0
pillow                    5.2.0            py37h08bbbbd_0
pip                       19.0.3                   py37_0
pkginfo                   1.4.2                    py37_1
pluggy                    0.7.1            py37h28b3542_0
ply                       3.11                     py37_0
prometheus_client         0.3.1            py37h28b3542_0
prompt_toolkit            1.0.15                   py37_0
psutil                    5.4.7            py37hfa6e2cd_0
pthread-stubs             0.4               h301d43c_1001    conda-forge
py                        1.6.0                    py37_0
pyasn1                    0.4.4            py37h28b3542_0
pyasn1-modules            0.2.2                    py37_0
pycodestyle               2.4.0                    py37_0
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.18                     py37_1
pycrypto                  2.6.1            py37hfa6e2cd_9
pycudadecon               0.1.2                    py37_0    talley
pycurl                    7.43.0.2         py37h7a1dbc1_0
pyflakes                  2.0.0                    py37_0
pygments                  2.2.0                    py37_0
pyhamcrest                1.9.0                    pypi_0    pypi
pyimagej                  0.4.0                 py37_1001    conda-forge
pyjnius                   1.2.0            py37ha31688d_0    conda-forge
pylint                    2.1.1                    py37_0
pyodbc                    4.0.24           py37h6538335_0
pyopenssl                 18.0.0                   py37_0
pyparsing                 2.2.0                    py37_1
pypher                    0.6.4                    pypi_0    pypi
pyqt                      5.9.2            py37h6538335_2
pysocks                   1.6.8                    py37_0
pytables                  3.4.4            py37he6f6034_0
pytest                    3.8.0                    py37_0
pytest-arraydiff          0.2              py37h39e3cac_0
pytest-astropy            0.4.0                    py37_0
pytest-doctestplus        0.1.3                    py37_0
pytest-openfiles          0.3.0                    py37_0
pytest-remotedata         0.3.0                    py37_0
python                    3.7.0                hea74fb7_0
python-dateutil           2.7.3                    py37_0
pytz                      2018.5                   py37_0
pywavelets                1.0.0            py37h452e1ab_0
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.4                    py37_0
pyyaml                    3.13             py37hfa6e2cd_0
pyzmq                     17.1.2           py37hfa6e2cd_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.4.4                    py37_0
qtconsole                 4.4.1                    py37_0
qtpy                      1.5.0                    py37_0
requests                  2.19.1                   py37_0
rope                      0.11.0                   py37_0
ruamel_yaml               0.15.46          py37hfa6e2cd_0
scikit-image              0.14.0           py37h6538335_1
scikit-learn              0.19.2           py37heebcf9a_0
scipy                     1.1.0            py37h4f6bf74_1
scyjava                   0.1.0                 py37_1001    conda-forge
seaborn                   0.9.0                    py37_0
send2trash                1.5.0                    py37_0
service_identity          17.0.0           py37h28b3542_0
setuptools                40.2.0                   py37_0
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.11.0                   py37_1
snappy                    1.1.7                h777316e_3
snowballstemmer           1.2.1                    py37_0
sortedcollections         1.0.1                    py37_0
sortedcontainers          2.0.5                    py37_0
sphinx                    1.7.9                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                    py37_1
spyder                    3.3.1                    py37_1
spyder-kernels            0.2.6                    py37_0
sqlalchemy                1.2.11           py37hfa6e2cd_0
sqlite                    3.26.0            hfa6e2cd_1000    conda-forge
statsmodels               0.9.0            py37h452e1ab_0
sympy                     1.1.1                    py37_0
tblib                     1.3.2                    py37_0
terminado                 0.8.1                    py37_1
testpath                  0.3.1                    py37_0
tifffile                  2019.1.4                 pypi_0    pypi
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                    py37_0
tornado                   5.1              py37hfa6e2cd_0
tqdm                      4.26.0           py37h28b3542_0
traitlets                 4.3.2                    py37_0
twisted                   18.7.0           py37hfa6e2cd_1
unicodecsv                0.14.1                   py37_0
urllib3                   1.23                     py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.14.1                   py37_0
wheel                     0.31.1                   py37_0
widgetsnbextension        3.4.1                    py37_0
win_inet_pton             1.0.1                    py37_1
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.10.11          py37hfa6e2cd_2
xlrd                      1.1.0                    py37_1
xlsxwriter                1.1.0                    py37_0
xlwings                   0.11.8                   py37_0
xlwt                      1.3.0                    py37_0
xorg-kbproto              1.0.7             h301d43c_1002    conda-forge
xorg-libx11               1.6.7             h301d43c_1000    conda-forge
xorg-libxau               1.0.9                h301d43c_0    conda-forge
xorg-libxdmcp             1.1.2             h301d43c_1007    conda-forge
xorg-xproto               7.0.31            h301d43c_1007    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7                hc54c509_2
zeromq                    4.2.5                he025d50_1
zict                      0.1.3                    py37_0
zlib                      1.2.11               h8395fce_2
zope                      1.0                      py37_1
zope.interface            4.5.0            py37hfa6e2cd_0

**Comment by tlambert03** [comment]
thanks Graham, I appreciate it, and I'd really like to figure this one out..  
one last test: I notice you've installed this into your base anaconda environment.  could you try creating a new minimal environment for it as follows?  at the anaconda prompt, type:
```
$ conda create -n testenv python=3.6 pycudadecon ipython
$ conda activate testenv
$ ipython

>>> from pycudadecon import decon
>>> im = 'path_to_your_image.tif'
>>> psf = 'path_to_your_psf.tif'
>>> result = decon(im, psf)
```
just want to rule out any conflicts with other things installed in your environment.

**Comment by gdellaire** [comment]
Hi Tally - no problem.  The env install did the trick using ipython!  And, holy mother of heyseus is the pyCUDAdecon algorithm fast on the Titan Xp - basically 30 ms an iteration.

I then installed Jupyter and ran it outside of Anaconda - and it is working great too. Thank you so much for your patience in working through this. A fresh environment did the trick. 
Best Graham

**Comment by gdellaire** [comment]
Hi Tally

I am about to post that the clean install did the trick and holy mother of god is it fast. 30 ms per iteration on the Titan Xp.
I also have a Titan V - so might boot up my Ubuntu box and try pyCUDAdecon on that system too.

I really appreciate your patients in helping me work through these issues.

I am only 6 months into Python coding and this is really helpful. I am super interested in CUDA accelerating some other decon algorithms (more to learn than anything else).

Can I pick your brain on how you implemented the GPU accelerated FFTs in your python wrapper? I would like to try replacing numpy FFT with CUDA accelerated FFTs in some different algorithms.

Best

Graham

--
___________________________________________

Graham Dellaire, Ph.D.
Director of Research, Department of Pathology
Professor, Departments of Pathology
and Biochemistry & Molecular Biology
Dalhousie University
P.O. BOX 15000
Halifax, Nova Scotia, Canada, B3H 4R2
Tel: (902)494-4730
Fax: (902)494-2519
E-mail: dellaire@dal.ca
Web: dellairelab.medicine.dal.ca<http://dellairelab.medicine.dal.ca>
Twitter: @DocDellaire<https://twitter.com/DocDellaire>
___________________________________________
This e-mail may contain confidential and/or privileged information for the sole use of the intended recipient. Any review or distribution by anyone other than the person for whom it was originally intended is strictly prohibited. If you have received this e-mail in error, please contact the sender and delete all copies. Opinions, conclusions or other information contained in this e-mail may not be that of the organization.


________________________________

**Comment by tlambert03** [comment]
Very interesting...
Someday perhaps I'll get around to figuring out exactly what it is in that base environment that causes the problem.  Until then, I'll add something to the readme and documentations warning people about using it in their base environments.

**Comment by tlambert03** [comment]
Very glad to hear it.  That WinError has been the bane of my existence over at LLSpy, but there the problem is a GPU-hogging conflict with spimagine… so I was definitely bummed that it was cropping up here too.  Good to at least narrow it down a bit though.

Should work on your Titan V ubuntu, but you’ll need to make sure to install llspylibs with cu10.0, and also make sure that your GPU driver is ≥410.48 on the linux.  To enforce the cuda version of the library install like this:

conda create -n env_name pycudadecon llspylibs=0.2.0=cu10.0

(Where “env_name” is whatever you want to name your environment).  And then, of course, you’ll need to “conda activate env_name” before using it.

There are many different ways to implement this sort of thing, each with tradeoff between how performant you might expect it to be, and how “pythonic” or high level you get to write it in.  In this case it was rather “ugly” and low level: the actual code was written in C++/CUDA, and I modified this library <https://github.com/dmilkie/cudaDecon> by Lin Shao to make it accessible to python.  The actual CUDA part is a set of kernels <https://github.com/dmilkie/cudaDecon/blob/master/RLgpuImpl.cu>, which is then called by some C++ functions <https://github.com/dmilkie/cudaDecon/blob/master/RL-Biggs-Andrews.cpp#L53>.  I then had to write some c++ code to expose those functions externally and compile them into a platform-specific shared library <https://en.wikipedia.org/wiki/Library_(computing)#Shared_libraries>, (a .dll file on windows, or .so file on linux).  A common way to “wrap” those shared libraries in python is to use ctypes <https://docs.python.org/3/library/ctypes.html>, and you can see one example of what that looks like in my code here <https://github.com/tlambert03/pycudadecon/blob/master/pycudadecon/libcudawrapper.py>.

However, there are much easier and higher-level ways to get started using the GPU in python… and I would encourage to look into pyCUDA <https://documen.tician.de/pycuda/>, which is a python wrapper of the basic NVIDIA CUDA API (so, no C-code required).  And then, moving up a level, there’s stuff like reikna <http://reikna.publicfields.net/en/latest/>, which is built on top of both pyCUDA and pyOpenCL (for those without NVIDIA GPUs) that provides an easy way to do things like the FFT <http://reikna.publicfields.net/en/latest/api/computations.html?highlight=fft#reikna.fft.FFT>.  That’s even easier to get started with (and maybe where you should go first if you want to replace the numpy FFT)… though, it’s worth pointing out that at some point, the biggest limitation in speed is getting things on to and off of the GPU.  So some care is required when using these higher level libraries to make sure that you leave the data on the GPU for the duration of the computations (for instance, all of the iterations in the deconvolution), otherwise the speed-up during the actual computation will be completely eclipsed by the amount of time it takes to move the data around.  You should also be aware of the gputools <https://github.com/maweigert/gputools> library, which is not CUDA, but uses OpenCL (works on any GPU) and has a lot of great functionality and functions already designed for you (and there, you’ll see examples of the actual OpenCL kernels right in the source code).

Hope that helps.

Best,
Talley

**Comment by gdellaire** [comment]
Thanks for this information Talley and all your help. 
I agree getting pyCUDA running (and probably NUMBA as well to accelerate all python code) is probably the best way to go. I would love to get into OpenCL and C++ (or C# - considering how much code is out there for RaspberryPi) as well. I am really enjoying Python and have got some good code down for moving between ImageJ and Python and back again, using pyImageJ and jnius.  The later is excellent for calling Java libraries and classes and could also be a way of accelerating FFTs, e.g. using JTransform (for multiprocessor) and JCufft for GPU. 

All the best - Graham

**Comment by VolkerH** [comment]
just to add to Talley's remarks. The Reikna FFT is actually wrapped by gputools and quite easy to use https://github.com/maweigert/gputools/tree/master/gputools/fft

**Comment by tlambert03** [comment]
hah.  somehow I didn't realize that was a public exchange... confused about how I got an email that doesn't appear here, yet my response does.   oh well!  thanks for adding that @VolkerH :)

**Comment by Baziki142** [comment]
haha, now I have the same error
